// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPStG6jF3_fy6mGkFEBTGKMGr5UD8LcLY',
    appId: '1:846784461671:web:6399d8372fe77455e78dc2',
    messagingSenderId: '846784461671',
    projectId: 'soramai',
    authDomain: 'soramai.firebaseapp.com',
    storageBucket: 'soramai.appspot.com',
    measurementId: 'G-KHC28HVBYH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNwbfSGtFztas5O9li9tu6iNd-WS1HWUE',
    appId: '1:846784461671:android:d6afe249fc5c593de78dc2',
    messagingSenderId: '846784461671',
    projectId: 'soramai',
    storageBucket: 'soramai.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSWhi9g_f7x3jiJzuB08TrgJBOyWWkKaA',
    appId: '1:846784461671:ios:7fe27616826942a7e78dc2',
    messagingSenderId: '846784461671',
    projectId: 'soramai',
    storageBucket: 'soramai.appspot.com',
    iosBundleId: 'com.swirx.soramai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSWhi9g_f7x3jiJzuB08TrgJBOyWWkKaA',
    appId: '1:846784461671:ios:7fe27616826942a7e78dc2',
    messagingSenderId: '846784461671',
    projectId: 'soramai',
    storageBucket: 'soramai.appspot.com',
    iosBundleId: 'com.swirx.soramai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPStG6jF3_fy6mGkFEBTGKMGr5UD8LcLY',
    appId: '1:846784461671:web:e417db78041e7c90e78dc2',
    messagingSenderId: '846784461671',
    projectId: 'soramai',
    authDomain: 'soramai.firebaseapp.com',
    storageBucket: 'soramai.appspot.com',
    measurementId: 'G-QQEM9DVXQE',
  );

}